[webserver]
port = ":8080"

# register data providers
[[providers]]
name = "test_postgis"
type = "postgis"
host = "localhost"
port = 5432
database = "rio_osm"
user = "postgres"
password = "postgres"

# maps are made up of layers
[[maps]]
 name = "rio_buildings"                                 # used in the URL to reference this map

        [[maps.layers]]
                name = "landuse"                        # will be encoded as the layer name in the tile
                        provider = "test_postgis"       # must match a data provider
                                minzoom = 0
                                        maxzoom = 22
                                                sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM buildings_mercator WHERE wkb_geometry && {{.BBox}}"
