version: '2'
services:

  postgres:
    environment:
      - DB_NAME=eventkit
      - DB_DATA_NAME=eventkit_data
      - DB_PASS=eventkit
      - DB_USER=eventkit
      - POSTGRES_USER=postgres
    build:
      context: .
      dockerfile: Dockerfile_postgres
    ports:
     - "5432:5432"

  elasticsearch:
   image: elasticsearch

  rabbitmq:
     image: rabbitmq

  django:
    build: .
    links:
      - elasticsearch
      - rabbitmq
    depends_on:
      - postgres 
    environment:
      - DATABASE_URL=postgres://eventkit:eventkit@postgres:5432/eventkit
      - DATASTORE_DATABASE_URL=postgres://eventkit:eventkit@postgres:5432/eventkit_datastore
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=eventkit.settings
      - ALLOWED_HOSTS=['django',]
    entrypoint: scripts/wait_for_postgres.sh postgres python manage.py runserver 0.0.0.0:8000 
    ports:
      - "8000:8000"

  celery:
    build: .
    links:
      - rabbitmq
      - elasticsearch
    depends_on:
      - postgres 
    command: celery worker -l DEBUG 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=geonode.settings
      - C_FORCE_ROOT=1
