version: '2'
services:

  postgres:
    image: postgres
    environment:
      - DB_NAME=eventkit
      - DB_DATA_NAME=eventkit_data
      - DB_PASS=eventkit
      - DB_USER=eventkit
      - POSTGRES_USER=postgres
#    build:
#      context: .
#      dockerfile: Dockerfile_postgres
  elasticsearch:
   image: elasticsearch

  rabbitmq:
     image: rabbitmq

  django:
    build: .
    links:
      - postgres
      - elasticsearch
      - rabbitmq
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - DATASTORE_DATABASE_URL=postgres://postgres:postgres@postgres:5432/eventkit_data
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=eventkit.settings
      - ALLOWED_HOSTS=['django',]
    ports:
      - "8000:8000"

  celery:
    build: .
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    command: celery worker -A -geonode.celeryapp:app -l DEBUG 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=geonode.settings
      - ALLOWED_HOSTS=['django',]
      - C_FORCE_ROOT=1
