version: '2'
services:

  postgres:
    image: postgres

  elasticsearch:
   image: elasticsearch

  rabbitmq:
     image: rabbitmq

  django:
    build:
        context: .
            dockerfile Dockerfile
    links:
      - postgres
      - elasticsearch
      - rabbitmq
    command: django-admin.py runserver 0.0.0.0:8000 --settings=eventkit.settings
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=geonode.settings
      - ALLOWED_HOSTS=['django',]
    ports:
      - "8000:8000"

  celery:
    build:
        context: .
            dockerfile Dockerfile
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    command: celery worker --app=geonode.celeryapp:app -B -l INFO
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=geonode.settings
      - ALLOWED_HOSTS=['django',]
      - C_FORCE_ROOT=1

  nginx:
    image: geonode/nginx
    links:
      - django
    ports:
      - "80:80"
